INSERT INTO SUBJECT (SUBJECT) VALUES ('Mathematics');
INSERT INTO SUBJECT (SUBJECT) VALUES ('History');
INSERT INTO SUBJECT (SUBJECT) VALUES ('Science');
INSERT INTO SUBJECT (SUBJECT) VALUES ('English');